include:
  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: urchin_right nice_view_adapter nice_view_gem

  # Dongle build:
  - board: nice_nano_v2
    shield: urchin_dongle dongle_display
    artifact-name: urchin_dongle
  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter nice_view_custom
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: urchin_left_peripheral
  - board: nice_nano_v2
    shield: urchin_right nice_view_adapter nice_view_custom
    artifact-name: urchin_right_peripheral
  # Setting reset
  - board: nice_nano_v2
    shield: settings_reset
