
# Enable the Central to fetch the battery level from the peripheral
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Enable the Central to report the peripheral's battery to the host (macOS)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Set reporting interval (e.g., every 60 seconds)
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_ZMK_EXT_POWER=y